name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: make test
      
  deploy:
    name: Deploy
    needs: test
    runs-on: self-hosted
    steps:
    - name: executing remote ssh commands
      run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 
          
     
